spring:
  main:
    banner-mode: off
  data:
    mongodb:
      authentication-database: ${MONGODB_AUTHENTICATION_DATABASE:shelter_database}
      username: ${MONGODB_USERNAME:shelterDatabaseUser}
      password: ${MONGODB_PASSWORD:e8anGQXUUQA2bc3tSd1N}
      database: ${MONGODB_DATABASE:shelter_database}
      host: ${MONGODB_HOST:193.193.229.71}
      port: ${MONGODB_PORT:27017}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:193.193.229.71:9092}

server:
  port: 8081
  servlet:
    context-path: "/lesson6/api/v1"

springdoc:
  swagger-ui:
    path: /docs/swagger-ui.html
    defaultModelsExpandDepth: -1
